ThilinaRajapakse/simpletransformers

simpletransformers/model.py

Accessing the `args` dictionary with dot notation gives an error in version 0.3.8, so I replaced it with braces.

Fix dict access error

---

simpletransformers/model.py

Using `simpletransformers` in a python notebook results into excessive printing due to `tqdm`. `tqdm` has a mode specifically for notebooks and a method of importing to detect whether it's operating in a notebook or not by importing from `tqdm.auto` instead of `tqdm` (see https://github.com/tqdm/tqdm#ipythonjupyter-integration).

Fix tqdm printing for python notebooks

---

simpletransformers/model.py

Changed args["silent"] to self.args["silent"] to avoid "TypeError: 'NoneType' object is not subscriptable" when calling model.fit()

Fix args["silent"] in model.py

---

README.md
simpletransformers/classification/classification_model.py

This pull requests reduce the amount of disk used during training. From what I see in the code, a change merged late December introduced saving every epoch. In our case, the Sagemaker instance filled its 50GB disk during training.
We might not be the only ones struggling with disk space during training so I set the default value of the flag to false.

No save every epoch

---

README.md

Since save_model_every_epoch default was set to True, that is now reflected in README.

README fix for save_model_every_epoch

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_label_classification_model.py

Proxies were not always found to be picked up by the underlying internet facing component that downloads the pre-trained models, config and tokenizer. The kwargs exposed through this change allows the consumer of `classification_model.py` and `multi_label_classification_model.py` to provide the proxies, control the file download mechanism, specify cache_dir and provide everything else that kwargs is looked up for in the respective 'for_pretrained' implementation.

Making path for proxies, download controls and other options

---

simpletransformers/classification/classification_model.py
simpletransformers/experimental/classification/classification_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py

As long as `cache_dir` and `output_dir` can be configured, if the path doesn't exist, should be created. 
`mkdir()` can create a single sub-directory and `makedirs()` creates all the intermediate directories

Folder creation fix

---

simpletransformers/classification/classification_model.py

The ClassificationModel constructor breaks when the default value for the `args` argument is set to `None` by default.

Fix ClassificationModel constructor when args is None

---

simpletransformers/classification/multi_label_classification_model.py
simpletransformers/custom_models/models.py

I added a `FlaubertForMultiLabelSequenceClassification` in `simpletransformers/classification/multi_label_classification_model.py` based on `XLMForMultiLabelSequenceClassification ` and modified `simpletransformers/custom_models/models.py` to allow the usage of FlauBERT.

Add  Multilabel support for FlauBERT model

---

simpletransformers/question_answering/question_answering_model.py
simpletransformers/question_answering/question_answering_utils.py

Because the empty answer ( which will occur when 'version_2_with_negative' is set to True) has an empty 'features', the previous code will meet a 'list out of index' error for trying indexing on an empty list.
Therefore, initialize the 'feature' by 'features' only when the 'pred.start_index' is greater than 0 can simply fix it. (pred.start_index > 0 means the answer is not empty.)
Moreover, for we do not need the variable 'feature' while the answer is empty, it's OK to do so.

Initialize the variable 'feature' from the variable 'features' only when the answer is non-empty

---

simpletransformers/config/global_args.py
simpletransformers/ner/ner_model.py
simpletransformers/ner/ner_utils.py

- Included the classification report for NER. It is useful for NER to understand the accuracy for each single tag. I included the classification report on the top of the `eval_results.txt` file.
- I fixed a bug occurring when non-printable characters are present inside the source file. In wikiNER dataset some non-printable characters are present and the associated label is 'O'. Anyway the tokenizer outputs a void token for them and so the length of the label list will be greater than the one of the tokenized words causing the assert to fail.

Classification report included and non printable character bug fixed

---

README.md

The `train` function of the `*_model.py` files use the arg `best_model_dir ` from `self.args` when `evaluate_during_training` is set to `True` to save the model checkpoints to a `best_model_dir`  directory when the `best_eval_loss` is `True` (or `best_correct_answers` for QA) which is calculated after every `evaluate_during_training_steps` and an epoch when `evaluate_during_training` is `True`. The default value of `best_model_dir` is `outputs/best_model` dir from where the script is executed. This is a problem when you change the `output_dir` in the args list when executing script, and the `best_model_dir` remains unchanged, leading to a new `outputs/best_model/ `dir directory outside of the new `args[output_dir]`
Currently, the `best_model_dir` is not listed in the args list in …

best_model_dir arg is used but not specified in the args list.

---

simpletransformers/config/global_args.py
simpletransformers/question_answering/question_answering_model.py

Give a default encoding as "utf-8" can avoid using "cp950" encoding on windows, which may occur an error while reading a json file with Chinese characters.

Set the default encoding as "utf-8" on QA model module

---

simpletransformers/classification/classification_model.py
simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py

The `training_progress_scores` in the `train` function of the `*_model.py` files are saved to the CSV file with the path `'training_progress_scores.csv' `string concatenated with `args["output_dir"]`. This leads to several problems:
1. The user has to supply the training backslashes in the `output_dir` arg. This can easily be forgotten by the user. With this PR, **the user does not have to worry about the trailing backslashes.**
2. The default value of the `args[output_dir]` is followed by a single trailing backslash, which is not compatible with the Windows paths, which require double backslashes (in string format), or a single forward slash. **`os.path.join()` makes it portable**.
3. Many codebases take `Pathlib.Path` as an input, which strips off the trailing backslash in the default …

remove concatenated paths with os.path.join()

---

README.md

Correct filename `pytorch_nodel.bin` to `pytorch_model.bin`.

docs: correct typo on README.md

---

simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/conv_ai/conv_ai_utils.py

Constructor can be passed a proxies argument which is picked up and used by load_examples_and_cache function when it calls the get_dataset() function.

(Fix) Fixed passing proxies kwargs into ConvAI model

---

simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py

This pull adds the automodel to QA, NER and language modeling.
Furthermore it sorts the model classes by alphabet.
So this library can automatically benefit from new models in the Transformers library

add automodel

---

simpletransformers/ner/ner_model.py

Currently, if we want to use the `predict` function of a NER model using a custom tokenizer, we have to use the parameter `split_on_space` and set it to False.
However, the `False` value is handled only at the beginning of the function and is forgotten at the end.
I am suggesting a simple and quick fix for this specific case.

Fix split_on_space handling for NER

---

README.md

Fix for typo in the brackets in the given example for "Minimal start for multilabel classification".

Fixing error in Minimal Start for Multilabel Classification

---

simpletransformers/classification/classification_model.py

Added to list of extra SEP token models as well. Longformer uses Roberta's tokenization.

Add longformer to list of space prefix model types

---

README.md
examples/language_generation/generate.py

The original code passes an argument named **length** to control the length of the textual output generated by GPT-2. This is the wrong parameter since the _LanguageGenerationModel_  does not have any private variables of this sort. The correct name for the parameter is **max_length** which is used by the _LanguageGenerationModel_  class in its constructor. 
Corrective changes were made to generate.py reflecting the same. The bug is now fixed and by passing a value for **max_length**, we can control the length of output generated by GPT-2.

[FIX] Fixed a bug in the parameter controlling the length of the text generated by GPT-2

---

examples/question_answering/lazy_qa.py
simpletransformers/config/model_args.py
simpletransformers/question_answering/question_answering_model.py
simpletransformers/question_answering/question_answering_utils.py

This PR implements Lazy Loading support for training QA models.
Special requirements:
- Requires `train_data` to be a `str` pointing to a [JSONL](http://jsonlines.org/) file.
- Lazy loading is only supported for training and not for evaluation.
Testing:
- A minimal testing script can be found at `examples/question_answering/lazy_qa.py`
To do:
- Update docs

Implements Lazy Loading for QA tasks

---

simpletransformers/question_answering/question_answering_utils.py

Hi Thilina,
This is a PR to fix the issue  #689 where you get error message 
`TypeError: squad_convert_example_to_features() missing 1 required positional argument: 'padding_strategy'` if you train a QuestionAnweringModel.
This happens because the function squad_convert_example_to_features() from huggingface https://github.com/huggingface/transformers/blob/77abd1e79fc37efb45bde0041f9dad0eabc55517/src/transformers/data/processors/squad.py#L91 added padding_strategy as a mandatory argument.

added the missing padding_strategy in the function squad_convert_examples_to_features

---

simpletransformers/classification/classification_model.py

For text classification:
- Add model, config and tokenizer. Associated BERTweet with `RobertaConfig`, following the merged PR on HF. 
- In case `model_name=='vinai/bertweet-base'`, assign the `bertweet_normalization` arg value to the `normalization` parameter of the tokenizer
```python
from simpletransformers.classification import ClassificationModel
import pandas as pd
model = ClassificationModel('bertweet','vinai/bertweet-base',normalization=True)
df = pd.read_csv(path_to_csv_with_tweets)
df = df[['text','labels']]
model.train_model(df)
```
- Include BERTweet for NER and other downstream tasks

Include BERTweet

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_label_classification_model.py
simpletransformers/classification/multi_modal_classification_model.py
simpletransformers/config/utils.py
simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/language_generation/language_generation_model.py
simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/language_representation/representation_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py
simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/t5/t5_model.py

Fixes #759.
I compared all versions of `wandb.Config` class listed in #759 and concluded that the `keys` method should work reliably for all of them.
Also, I've just installed `simpletransformers` from my branch and no longer experience the issue.

Fix compatibility with different versions of wandb when sweeping

---

simpletransformers/t5/t5_model.py

To remove 
> UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.

t5 get_last_lr() warning

---

simpletransformers/t5/t5_utils.py

In t5_utils.py **truncation should be True** for token encoding **when max_len is provided** in order avoid infinite warnings which crashes the colab notebook and notebook running on local machine although it runs fine on kaggle. 
Screenshot is attached [](url)
[Notebook to reproduce the behavior, please run this on colab  or local machine.](https://colab.research.google.com/drive/1Zm83z29wFrRi03tQP4ZEky003vy-c4_X#scrollTo=1-GJELrbSZ15&uniqifier=1)  @ThilinaRajapakse

truncation=True in t5_utils

---

simpletransformers/t5/t5_model.py

I propose to modify 1 argument and to add 2 arguments (optional) to the T5model class:
- model_name: becomes optional, if it is not set then T5 model without pre-trained weights is instantiated
- config: it has to be passed only if model_name is not provided (otherwise it is overwritten), it allows instantiating T5ForConditionalGeneration without passing a pre-trained model ([example](https://github.com/huggingface/transformers/issues/1714)) 
- tokenizer: optional, custom tokenizer to pass (it can be useful in case of, for example, additional tokens)

T5 update to handle different scenario

---

simpletransformers/classification/classification_model.py

Doing WandB sweeps with `simpletransformers` seems to have some issues (#817, #545 and possibly more).
Some of these issues seem to be caused by the call to `wandb.init()` in the [train method](https://github.com/ThilinaRajapakse/simpletransformers/blob/0cf4ffcdf83ee339f657c10789542e892d3ba2b4/simpletransformers/classification/classification_model.py#L540).
For sweeps it is mandatory to already having called `wandb.init()` outside of the `simpletransformers` code, namely in the method that the sweep is looping over to create a number of runs in the sweep. We need to do this so we can pass `wandb.config` as the `sweep_config` parameter to create a `ClassificationModel`. Roughly like this:
```python
sweep_config = {...}
sweep_id = wandb.sweep(sweep_config, project="My Project")
model_args = …
```

Fixing WandB sweep issues by suppressing `wandb.init()` in `train()`

---

simpletransformers/language_representation/representation_model.py

Stemming from comments to PR #834 I propose this PR with a number of improvements to RepresentationModel:
- If combine_strategy is an int value, then the token at the index identified by that value is returned by encode_sentences.
This allow to select special tokens, such as [CLS] (index 0) or the last one (index -1).
- np.concatenate is executed only once on all the batches of embeddings, which are temporarily collected in a list. 
This is much more memory and time efficient than invoking np.concatenate after every loop, which requires reallocation of all the objects collected so far at every loop.
- Added tqdm to encode_sentences, to give visual feedback on the process.

Improvement to RepresentationModel

---

simpletransformers/seq2seq/seq2seq_model.py

Added missing argument 'return_tensors="pt",' to input_ids initialisation of mbart models. Using mbart for prediction before lead to "list has no to attribute" error.

MBart predict function error

---

simpletransformers/ner/ner_model.py

I increased the digits precision for the NER evaluation to 4 digits (vs 2 of the previous version). This ensures to have a good final report that can be translated into percentages.

Classification report for NER eval with 4 digits precision

---

.gitignore
simpletransformers/classification/classification_model.py

Fixes my issue #784 where I had two problems evaluating a MultiLabelClassificationModel
```python
model = MultiLabelClassificationModel()
result, model_outputs, wrong_predictions = model.eval_model(valid_df)
```
1. currently all inputs are returned as ```wrong_predictions``` because the line ```mismatched = labels != preds``` is run on the raw label probabilities, as [1, 0] != [0.8, 0]. Bug fix would compare the values after converting probabilities into 1 or 0, based on a threshold (default is 0.5)
```python
result, model_outputs, wrong_predictions = model.eval_model(valid_df, threshold=0.6)
```
2. we want send a custom threshold=0.6 in kwargs, and evaluate it before ```mismatched = labels != preds```. The code ```extra_metrics[metric] = func(labels, preds)``` tries to call all kwargs …

wrong_predictions eval and threshold in MultiLabelClassificationModel

---

docs/_docs/35-convAI-minimal-start.md

Broken link: https://simpletransformers.ai/docs/convAI-minimal-start/
Works with: https://simpletransformers.ai/docs/convAI-examples/
Guided by consistency being king, I presume it was better to change the permalink than change the destination URL of the link.

Update permalink to match that of `navigation.yml`

---

simpletransformers/ner/ner_utils.py

args.silent was not used for converting the features of an NERModel when use_multiprocessing is set to false.
Thanks a lot for the hard work and the awesome library!

Use args.silent when use_multiprocessing is False for NERModel

---

simpletransformers/classification/multi_label_classification_model.py
simpletransformers/custom_models/models.py

- Add BERTweet to multilabel classification (following #885 )
```python
from simpletransformers.classification import MultiLabelClassificationModel
import pandas as pd
import logging
train_data = [['Example sentence 1 for multilabel classification.', [1, 1, 1, 1, 0, 1]], ['This is another example sentence. ', [0, 1, 1, 0, 0, 0]]]
train_df = pd.DataFrame(train_data, columns=['text', 'labels'])
model = MultiLabelClassificationModel('bertweet', 'vinai/bertweet-base', num_labels=6, args={'num_train_epochs': 5})
model.train_model(train_df)
```

Add BERTweet for multilabel classification

---

simpletransformers/classification/classification_model.py

Uncommenting these appends, which is necessary to generate the full set of predictions when `sliding_window=True`.

Fixing prediction output for sliding_window=True and output_hidden_states=True

---

simpletransformers/classification/classification_model.py
simpletransformers/config/model_args.py

This PR makes it possible to add special additional tokens via ClassificationArgs . e.g for conversational AI applications one can add [USR] and [SYS] special tokens via a configuration like the following 
model = ClassificationModel('xlmroberta','xlm-roberta-base', num_labels=3, args={'special_tokens_list':["[USR]","[SYS]"]})

Add special tokens to tokenizer through Args 

---

simpletransformers/classification/classification_model.py

So far, the default metrics were threshold-specific (default=0.5). Now, they include non-threshold specific metrics for binary classification, namely the Area under the ROC curve (AUROC) and the Area under the Precision-Recall curve (AUPRC). This can come in handy when doing early stopping and mostly caring about AUROC.
To test, install my fork and run the following:
```python
from simpletransformers.classification import ClassificationModel, ClassificationArgs
import pandas as pd
import logging
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)
train_data = [
["Aragorn was the heir of Isildur", 1],
["Frodo was the heir of Isildur", 0],
]
train_df = pd.DataFrame(train_data)
train_df.columns = …
```

Add AUROC and AUPRC as default metrics for binary classification

---

simpletransformers/config/model_args.py

There is an issue initializing language generation models
```
from simpletransformers.language_generation import LanguageGenerationModel
model = LanguageGenerationModel("gpt2", "monsoon-nlp/sanaa")
> AttributeError: “LanguageGenerationArgs” object has no attributes “special_tokens_list”
```
The problem was introduced with commit 483e90ed950  which checks special_tokens_list in LanguageGenerationModel, but did not include it in the LanguageGenerationArgs class.
There are two other subclasses of ModelArgs which do not have special_tokens_list; I think they are unaffected, so we should add it to LanguageGenerationArgs only, and not on the ModelArgs level

Add special_tokens_list to LanguageGenerationArgs

---

simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/seq2seq/seq2seq_utils.py

1. In transformers < 4.2.0, there is a bug in mbart model, 'model.encoder.embed_positions.weight' and 'model.decoder.embed_positions.weight' will not be saved. So in inference stage, the model is damaged.
2. The function "transformers.models.bart.modeling_bart.shift_tokens_right" has different interface in transformers >= 4.2.0.

fix mbart bug.

---

simpletransformers/classification/classification_utils.py

Fixes #972 
On the first training epoch, things work OK, but ```label = features.pop("label")``` removes the label from the original feature.  On the second epoch, we no longer can access the label.
By using dict.copy(), we avoid editing the original row

Avoid removing label from original data

---

simpletransformers/language_modeling/language_modeling_model.py

A possible fix for [this issue](https://github.com/ThilinaRajapakse/simpletransformers/issues/1002) regarding loading of models without GPU. This has been tested with an Electra model pretrained on GPU, as described on the issue.

Fix bug when loading pretrained model on machine without GPU

---

simpletransformers/ner/ner_model.py

There is no explicit reason to set the option. Removing it and let the runtime decide it did improve performance on multi-core CPUs.

Rmove intra_op_num_threads=1 for ONNX runtime

---

docs/_docs/24-t5-specifics.md

In the t5 specifics doc the train_data is copy-pasted twice but the second should be eval_data. 
Eval data is used at the bottom 
```
model.train_model(train_df, eval_data=eval_df, matches=count_matches)
print(model.eval_model(eval_df, matches=count_matches))
```
But had an unknown variable warning since it was never specified.

Fix duplicate variable/unknown variable eval_df

---

docs/_docs/24-t5-specifics.md

In the t5 specifics doc, the labels for the binary classification class should be formatted as strings and not integers.
Using integers will raise:
```
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
```
Fixes #1147

fix incorrect data type for output label

---

simpletransformers/ner/ner_utils.py

It seems to me that typo occurred in variable name `splits` so I fixed it.
Also I guess I will be mor efficient to use `.split()`(with no separator it removes all space characters for instance \t and \n) instead of 4 x `.replace('\n', '')`

fix typo in splits and change split separator to remove '\n'

---

simpletransformers/ner/ner_model.py

ONNX execution providers list fails when a fallback option is specified as an NERModel initialization parameter a tuple with fallback options.  E.g. ('CUDAExecutionProvider', 'CPUExecutionProvider').  The bug double wraps the list of providers causing the fallback to fail and ONNX InferenceSession method to fail.

ONNX execution provider list fails when a fallback is specified

---

.gitignore
simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_modal_classification_model.py
simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py
simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/t5/t5_model.py

This PR adds a new attribute `wandb_run_id` to the models, this allows users to grab the run id after the training is finished and use it to extend the current logging features provided.

Added `wandb.run.id` to model attributes

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_label_classification_model.py

This PR refactors loss calculation so this is identical to `NERModel`.
This PR makes `transformer_models` deprecated. 
Also I have changed import `from simpletransformers.custom_models.models import ElectraForSequenceClassification` to
`ElectraForSequenceClassification`, I am not entirely sure about what this change will bring (I actually think this is causing some issues with compatibility with transformers #571 )so this needs review @ThilinaRajapakse .
Other tan that I have added `losses` module, for future feature that I am working on. I have implemented part of in in my fork and different loss actually brings better performance (if you are interested in using focal loss now you can refer to: https://github.com/Zhylkaaa/simpletransformers/tree/dice_loss)

Rafactor classification model loss calculation

---

simpletransformers/ner/ner_utils.py

Fixes ==> UnboundLocalError: local variable 'example' referenced before assignment
Mostly happens during eval.
<module>
dev_result, dev_model_outputs, dev_predictions = best_model.eval_model(eval_data=dev_file_clean)
File "/opt/anaconda3/envs/st2/lib/python3.9/site-packages/simpletransformers/ner/ner_model.py", line 1146, in eval_model
result, model_outputs, preds_list = self.evaluate(
File "/opt/anaconda3/envs/st2/lib/python3.9/site-packages/simpletransformers/ner/ner_model.py", line 1200, in evaluate
for batch in tqdm(
File "/opt/anaconda3/envs/st2/lib/python3.9/site-packages/tqdm/std.py", line 1185, in __iter__
for obj in iterable:
File "/opt/anaconda3/envs/st2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
data = self._next_data()
File …

Fixes unbound local error in ner_utils.py

---

simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_utils.py

Required user defined tokens for XLMRoberta  and SentencePiece pretrained models were not accounted for in the vocabulary size.  Subsequently, the config.json vocab_size was off by 2 for XLMRoberta and 3 for BigBird.
This can be manually fixed for any existing trained models by manually editing the config.json

Language modeling sentence piece bugfix

---

simpletransformers/conv_ai/conv_ai_model.py

Hi Thilina,
the function ConvAIModel.train_model() has eval_file as its parameter, but it is not used when it tries to load the dataset for the evaluation even it is defined, instead it uses the default dataset (PERSONACHAT_URL).

Use eval_file if it is defined in train_model()

---

simpletransformers/language_modeling/language_modeling_model.py

Quotes around user_defined_symbols are required If running sentencepiece trainer from the command line
As of, not sure when, when calling the sentencepiece trainer via the api, the quotes are added to the first and last symbol
This fix corrects the vocabulary generation for downstream tasks
@ThilinaRajapakse this is a fairly urgent pull request

Bugfix for SentencePiece trainer

---

simpletransformers/ner/ner_model.py

@ThilinaRajapakse if split_on_spaces is false and the input is pre-tokenized, tokenizer.batch_encode_plus now requires a parameter to process the input data.

bugfix for pre-tokenized onnx predict

---

simpletransformers/language_modeling/language_modeling_model.py

BigBird bugfix where training dataset samples were being truncated at 510
<pad> token was missing when generating a bigbird sentencepiece vocabulary

bigbird training dataset samples were truncated

---

simpletransformers/retrieval/retrieval_utils.py

Fix error "name 'amp' is not defined" when using retrieval model with args.fp16=False

Fix bug: Retrieval model when using fp16=False

---

simpletransformers/question_answering/question_answering_model.py

In question_answering_model.py, the classes in MODEL_CLASSES for key 'auto' are in the wrong order. It should be config, model, tokenizer.

Fix wrong order of model classes for key auto in question answering

---

simpletransformers/language_modeling/language_modeling_model.py

I removed the extra quotes in the sentencepiece trainer parameters for XLMRoberta language models special tokens. I had done this before for bigbird.
Removed the bigbird -3 vocabulary size adjustment, after Dec 28th sentencepiece update this is no longer necessary.

XLMRoberta sentencepiece special token bugfix

---

simpletransformers/classification/classification_model.py

eval_examples can be 1) a list of InputExamples, 2) a tuple of two or three lists, with the first one or two columns as the text columns. Only the first case is handled currently.
Fixes #1139

Return wrong_preds correctly for eval_model()

---

simpletransformers/ner/ner_model.py

After going through the code I observed.
1. For the PyTorch model, if a word is split using tokenization (Eg: running - run + ##ning) then except for the first index everything (in that split token) is -100 in out_label_ids.
2. For the ONNX Model, only the first and last index values in out_label_ids were -100 because they were CLS and SEP.
So, I copied some code from PyTorch prediction and make some changes to make it work for ONNX.
However, it is only tested for a Single Prediction.

fixed NER onnx support

---

simpletransformers/ner/ner_utils.py

line 475
In p.imap, `chunksize` means that the objects in `examples` are allocated to each process with the size of `chunksize`, but each object in `examples` has been chunked before, resulting in almost all data running in a single process.
For example, when chunksize=500 and the amount of data is 5000, assuming process_count is 4, then examples should be a 10*500 list. When entering p.imap, the same chunksize parameter will consider 500*500 pieces of data as a chunk, which results in almost all data being completed in one process, resulting in the same speed as a single process or even slower.
So my way of handling it is not to use the chunksize parameter in imap, because the data is already chunked in the previous step.

Improve convert_examples in mutiprocess mode

---

simpletransformers/ner/ner_utils.py

linecache is 1 relative not 0.  
The PR fixes the first sample being prepended with an empty unigram. Subsequently the unigram causes a one unigram shift as compared to the original data and labels.
Affects NER training and eval.
Workaround is to set args.lazy_loading_start_line=1 until this bugfix is merged.

ner_utils lazy_loading_start_line default injects unigram into first sample

---

examples/text_classification/lazy_loading_regression.py
simpletransformers/classification/classification_model.py

There seemed to be a few issues using lazy loading.  The current example didn't work, so I had to make the following changes. The first error that I would run into when trying to do lazy loading for Text Classification was:
```
Traceback (most recent call last):
File "lazy_loading_regression.py", line 49, in <module>
model.train_model("data/regression_train.tsv")
File "/Users/saint/code/simpletransformers/simpletransformers/classification/classification_model.py", line 605, in train_model
global_step, training_details = self.train(
File "/Users/saint/code/simpletransformers/simpletransformers/classification/classification_model.py", line 877, in train
inputs = self._get_inputs_dict(batch)
File "/Users/saint/code/simpletransformers/simpletransformers/classification/classification_model.py", …
```

Bugs related to lazy loading

---

docs/_docs/05-classification-models.md

Saw some broken/incomplete links in the docs at https://simpletransformers.ai/docs/classification-models/ . So here is a quick fix. If you prefer not to take a PR for this, just ignore!

suggested fixes for links to supported model types

---

docs/_docs/05-classification-models.md
docs/_docs/06-classification-data-formats.md
simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_label_classification_model.py
simpletransformers/custom_models/models.py

The `predict` method for `ClassificationModel`  as well as `MultiLabelClassificationModel` for `layoutlm` model is broken. Also improved data format documentation, specifically, for `layoutlm` model(s).  
Potential Reviewers: @ThilinaRajapakse, @whr778

support for LLMv1 prediction for classification

---

simpletransformers/seq2seq/seq2seq_model.py

Fixes bug which prevents Marian models saved with `Seq2Seq.save_model` from being loaded

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_modal_classification_model.py
simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/experimental/classification/classification_model.py
simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py
simpletransformers/question_answering/question_answering_utils.py
simpletransformers/retrieval/retrieval_model.py
simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/t5/t5_model.py

Transformers has deprecated AdamW and issues warnings to use the torch.optim.AdamW package when called
API is the identical
I ran with NERModel

AdamW transformers deprecation

---

requirements-dev.txt
simpletransformers/classification/classification_utils.py
simpletransformers/losses/focal_loss.py
simpletransformers/ner/ner_utils.py

Suggested python 3.10 support fixes for #1426 . I have tested the fixes (using `pytest tests`) with Python **3.8.10** and **3.10.5** BUT I had to disable the `longformer-allenai/longformer-base-4096` tests because these are very memory-hungry and get killed by OOM killer on my system. So if you make use of this PR please test first.
Note: Also had to bump the versions of `pytest` and `black` in *requirements-dev.txt* in order to get these working. This is in a separate commit. Please reject this part if there is some reason to hold the versions back.

python 3.10 support

---

simpletransformers/classification/classification_model.py
simpletransformers/ner/ner_model.py

Suggested fix for old unresolved issue #1135 . Ensures continued compatibility with next major version of wandb.
Tested with wandb **0.10.32** (minimum version required in *setup.py*) and **0.13.4** (latest). Works for both.

Fix wandb deprecated plots
