simpletransformers/model.py

Added a silent argument to suppress print and tqdm outputs in console
Useful when trying to demo a frontend without showing backend details
Default "silent": False, so default behavior is the same as current version

Added silent arg for console outputs (print, tqdm)

---

README.md

the `evaluate_during_training` option is already written right above.

remove duplicate option in args

---

CHANGELOG.md
setup.py
simpletransformers/classification/multi_label_classification_model.py

Supporting evaluation measures during the training of multilabeling. (BTW, it looks like that you missed 0.15.6 description in Changelog file.)

Multilabel training evaluation

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/classification_utils.py
simpletransformers/experimental/classification/classification_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py
simpletransformers/question_answering/question_answering_utils.py

solves https://github.com/ThilinaRajapakse/simpletransformers/issues/128
Uses the recommended initialization of the NullHandler(), see: https://docs.python.org/3/howto/logging.html#library-config

changing print statements to logging calls

---

README.md
simpletransformers/experimental/classification/classification_model.py

fix typos in documentation

---

.all-contributorsrc
README.md

Reverts ThilinaRajapakse/simpletransformers#171

Revert "docs: add for as a contributor"

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/transformer_models/flaubert_model.py

Hi,
This pull request aims to add support for FlauBERT model as described in the issue #217.
Thanks

Add support for FlauBERT model

---

simpletransformers/question_answering/question_answering_model.py

Switching to logging will be more useful to users who want to use simpletransformers in console-based applications. Except for running loss, print statements within question_answering_model.py have been replaced with logging.

Update QuestionAnsweringModel Logging

---

simpletransformers/ner/ner_model.py

Avoid to create the cache dir if caches have not to be used

Cache dir not created if no_cache is True

---

.gitignore
Untitled.ipynb
simpletransformers/conv_ai/conv_ai_model.py

Missed this in the other merge. Interact method also calls get_dataset.

Extension of #311 - passing the proxies to interact method

---

simpletransformers/classification/multi_label_classification_model.py

Looks like the kwargs are not passed to parent train method

Update multi_label_classification_model to passs kwargs 

---

CHANGELOG.md
simpletransformers/config/global_args.py
simpletransformers/seq2seq/__init__.py
simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/seq2seq/seq2seq_utils.py

Quick script for testing:
```
import logging
import pandas as pd
from simpletransformers.seq2seq import Seq2SeqModel
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)
train_data = [
["one", "1"],
["two", "2"],
]
train_df = pd.DataFrame(train_data, columns=["input_text", "target_text"])
eval_data = [
["three", "3"],
["four", "4"],
]
eval_df = pd.DataFrame(eval_data, columns=["input_text", "target_text"])
model_args = {
"reprocess_input_data": True,
"overwrite_output_dir": True,
"max_seq_length": 10,
"train_batch_size": 2,
"num_train_epochs": 100,
"save_eval_checkpoints": False,
"save_model_every_epoch": False,
"evaluate_generated_text": True,
"evaluate_during_training": True, …
```

Seq2seq Model Implementation

---

setup.py
simpletransformers/seq2seq/seq2seq_model.py

rename marian tokenizer
set transformers to version 2.9.1

marian renaming

---

docs/_docs/09-regression.md

Update doc regression small typo

[DOC] Update doc regression small typo

---

simpletransformers/language_modeling/language_modeling_model.py

Electra fix

---

simpletransformers/question_answering/question_answering_utils.py

Hi @ThilinaRajapakse , please review the change. thanks :)

Return probabilities in predict function in QA model

---

.github/ISSUE_TEMPLATE/feature_request.md

This PR adds an issue template for feature requests, to make it easier to distinguish it from other issues

add feature request remplate

---

simpletransformers/classification/classification_model.py

Fixing ClassificationModel.predict to properly handle output_hidden_states=True for multiple examples

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/classification_utils.py

Adding prefix space for Roberta and similar tokenizers

---

simpletransformers/classification/classification_utils.py

#497 
make sure the arg of "data_type_extension" is properly parsed

fix data_type_extension check

---

simpletransformers/config/model_args.py
simpletransformers/language_modeling/language_modeling_model.py

this allow to configure the mlm tokenizer

Tokenizer model args

---

simpletransformers/question_answering/question_answering_model.py

This PR adds Bart for Question answering.
At the moment there is no huggingface release containing this class

Bart for question answering

---

README.md

add how to update docs instructions to readme.md under new section: how to contribute

add how to contribute section to readme

---

simpletransformers/conv_ai/conv_ai_model.py

Fix conv_ai fp16 training using undefined **inputs variable as model input

Fix conv_ai fp16 training bug

---

README.md
simpletransformers/classification/classification_model.py
simpletransformers/classification/classification_utils.py
simpletransformers/config/model_args.py

This PR adds code to dynamically quantize and thread tune to increase throughput when using classification models in production. 
Also, this PR adds code to avoid padding to max length during the online inference of the classification model. This change reduced latency significantly during CPU inference.

Add Dynamic quantization, thread tuning and avoid padding during online inference

---

docs/_docs/04-classification-specifics.md
simpletransformers/classification/multi_label_classification_model.py
simpletransformers/custom_models/models.py
tests/test_classification.py

Hi,
This pull request aims to add support for multilabel classification with the CamemBERT model as described in the issue #149.
Thanks

Add Multilabel support for CamemBERT model

---

simpletransformers/config/model_args.py
simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/t5/t5_model.py

this PR fixes #747 and adds spacial tokens functionality (probably should be improved for Roberta models)
and adds some more control over tokenisation process and special tokens support (sorry for typo) 
(personally used special tokens to separate keywords, as used in https://github.com/nlpyang/PreSumm/tree/master for summaries)

Encoder decoder fixes and spacial token functionality

---

README.md

"bart-large" is ""facebook/bart-large" on huggingface model hub

Update decoder name for bart

---

simpletransformers/language_representation/representation_model.py

Adding movement to selected device

---

simpletransformers/ner/ner_model.py

This is a solution to the problem I faced in #812

fixed issue 812

---

simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_modal_classification_model.py
simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py
simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/t5/t5_model.py

Fix evaluate_during_training train mode

---

docs/_data/navigation.yml

Langauge generation → Language generation

Fixed a typo in website

---

simpletransformers/ner/ner_utils.py

Fix the problem with ner lazy loading

---

simpletransformers/classification/classification_model.py

Fixed sliding windows tie breaking implementation

---

simpletransformers/ner/ner_model.py

Fixes issues where token_ids are required for onnx predict and moves data caching and batching which are performed for torch and not for onnx.
Fixes issues:
#1009
#1010

Fixes ONNX predict for models with token_type_ids 

---

docs/_docs/04-classification-specifics.md
simpletransformers/classification/classification_model.py

- added BigBird for regular sequence classification (not multilabel)
- modified the docs accordingly

Add BigBird for classification

---

docs/_docs/03-usage.md
docs/_docs/25-t5-model.md

Improve documentation

---

docs/_docs/04-classification-specifics.md
docs/_docs/12-ner-specifics.md
simpletransformers/classification/classification_model.py
simpletransformers/classification/multi_label_classification_model.py
simpletransformers/conv_ai/conv_ai_model.py
simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_model.py
simpletransformers/question_answering/question_answering_model.py
simpletransformers/seq2seq/seq2seq_model.py
simpletransformers/t5/t5_model.py

Adds Hebert model - SOTA for polish language

Add herbert

---

simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_utils.py

Added BigBird and Google native sentencepiece tokenizer.  HF Tokenizers sentencepiece is not compatible with bigbird.
Pretrained two contextual language models to test code.

Bigbird language model and Sentencepiece tokenizer

---

README.md

I know, the earth was not gonna stop revolving because of that ;)

With using conda -> Using conda

---

simpletransformers/classification/classification_model.py

This change follows the code in ner_model.py to use the appropriate inputs for the classification model when predicting for onnx.

Adapt classification model onnx code to use appropriate inputs for model

---

simpletransformers/seq2seq/seq2seq_model.py

The epoch number is shown wrong in running lose info.

Wrong epoch number info

---

setup.py
simpletransformers/classification/classification_model.py

fix bug when iterating dict

---

docs/_docs/28-seq2seq-specifics.md

Fix typo in 28-seq2seq-specifics.md

---

docs/_docs/05-classification-models.md
docs/_docs/13-ner-model.md
docs/_docs/17-qa-model.md
docs/_docs/25-t5-model.md
docs/_docs/29-seq2seq-model.md
docs/_docs/33-convAI-model.md
docs/_docs/42-multi-modal-classification-model.md
docs/_docs/55-retrieval-model.md

Fixes links in documentation web site

Fix additional metrics documentation link

---

simpletransformers/ner/ner_model.py
simpletransformers/ner/ner_utils.py

@ThilinaRajapakse Fixed a minor bug which does not honor the predict method split_on_space flag during onnx prediction causing an exception to be thrown.

Predict split_on_space flag bugfix

---

docs/_docs/04-classification-specifics.md
docs/_docs/12-ner-specifics.md
docs/_docs/20-lm-specifics.md
examples/text_classification/multiclass_classification.py
examples/text_classification/multilabel_classification.py
simpletransformers/classification/classification_model.py
simpletransformers/classification/classification_utils.py
simpletransformers/classification/multi_label_classification_model.py
simpletransformers/custom_models/models.py
simpletransformers/language_modeling/language_modeling_model.py
simpletransformers/ner/ner_model.py
simpletransformers/ner/ner_utils.py

@ThilinaRajapakse I added rembert and LayoutLM2 support.

LayoutLM2 and rembert

---

docs/_docs/27-t5-minimal-start.md

change target_text to string type in T5 minimal start

change target_text to string type in T5 minimal start
